edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"

# Import organization
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
imports_layout = "Vertical"

# Function and struct formatting
fn_params_layout = "Tall"
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"
match_arm_blocks = true
match_arm_leading_pipes = "Never"
force_explicit_abi = true

# Comments and documentation
wrap_comments = true
comment_width = 80
normalize_comments = true
normalize_doc_attributes = true

# String and literal formatting
format_strings = true
format_code_in_doc_comments = true

# Trailing commas and semicolons
trailing_comma = "Vertical"
trailing_semicolon = true
use_field_init_shorthand = true

# Spacing and alignment
space_before_colon = false
space_after_colon = true
spaces_around_ranges = false
binop_separator = "Front"
remove_nested_parens = true

# Error handling and control flow
empty_item_single_line = true
fn_single_line = false
where_single_line = false

# Type formatting
type_punctuation_density = "Wide"
struct_field_align_threshold = 0

# Macro formatting
format_macro_matchers = true
format_generated_files = false

# Miscellaneous
unstable_features = false
disable_all_formatting = false
skip_children = false
