name: Update Changelog

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'examples/**'
      - 'tests/**'
  pull_request:
    branches:
      - main

jobs:
  changelog:
    name: Check/Update Changelog
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install git-cliff
        run: |
          CLIFF_VERSION="2.6.0"
          ARCH="x86_64-unknown-linux-gnu"
          curl -L "https://github.com/orhun/git-cliff/releases/download/v${CLIFF_VERSION}/git-cliff-${CLIFF_VERSION}-${ARCH}.tar.gz" | tar xz
          sudo mv git-cliff /usr/local/bin/
          git-cliff --version
      
      - name: Generate changelog
        run: |
          git-cliff --config cliff.toml --output CHANGELOG.md --unreleased
      
      - name: Check if changelog needs update
        run: |
          if [ -n "$(git status --porcelain CHANGELOG.md)" ]; then
            echo "❌ CHANGELOG.md is out of date. Please run 'make changelog' and commit the changes."
            git diff CHANGELOG.md
            exit 1
          else
            echo "✅ CHANGELOG.md is up to date"
          fi

