name: Release

on:
  push:
    tags:
      - 'v*'  # Triggers on tags like v0.1.0, v1.2.3, etc.

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Publish to crates.io and create GitHub release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy
      
      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      
      - name: Run tests
        run: cargo test --verbose --all-targets
      
      - name: Extract version from tag
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Tag version: $VERSION"
      
      - name: Verify version matches Cargo.toml
        run: |
          CARGO_VERSION=$(grep '^version =' Cargo.toml | cut -d'"' -f2)
          TAG_VERSION="${{ steps.get_version.outputs.version }}"
          if [ "$CARGO_VERSION" != "$TAG_VERSION" ]; then
            echo "Error: Cargo.toml version ($CARGO_VERSION) does not match tag version ($TAG_VERSION)"
            exit 1
          fi
          echo "Version match confirmed: $CARGO_VERSION"
      
      - name: Install git-cliff
        run: |
          CLIFF_VERSION="2.6.0"
          ARCH="x86_64-unknown-linux-gnu"
          curl -L "https://github.com/orhun/git-cliff/releases/download/v${CLIFF_VERSION}/git-cliff-${CLIFF_VERSION}-${ARCH}.tar.gz" | tar xz
          sudo mv git-cliff /usr/local/bin/
          git-cliff --version
      
      - name: Get default branch
        id: default_branch
        run: |
          BRANCH=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT
          echo "Default branch: $BRANCH"
      
      - name: Checkout main branch
        run: |
          git checkout ${{ steps.default_branch.outputs.branch }} || git checkout main || git checkout master
      
      - name: Generate changelog
        id: changelog
        run: |
          git fetch --tags --unshallow 2>/dev/null || git fetch --tags
          git-cliff --config cliff.toml --output CHANGELOG.md --tag v${{ steps.get_version.outputs.version }}
          # Extract release notes for this version
          VERSION="${{ steps.get_version.outputs.version }}"
          NOTES=$(awk "/^## \[v?$VERSION\]/,/^## \[/ {if (/^## \[/ && NR>1) exit; print}" CHANGELOG.md | head -n -1 || \
                  awk "/^## \[v?$VERSION\]/,/^$/" CHANGELOG.md)
          {
            echo 'notes<<EOF'
            echo "$NOTES"
            echo 'EOF'
          } >> $GITHUB_OUTPUT
          cat CHANGELOG.md
      
      - name: Commit and push changelog
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          if ! git diff --staged --quiet; then
            git commit -m "chore: update changelog for v${{ steps.get_version.outputs.version }}"
            git push origin ${{ steps.default_branch.outputs.branch }}
          fi
      
      - name: Build release
        run: cargo build --release --verbose
      
      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: cargo publish --verbose --no-verify
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release v${{ steps.get_version.outputs.version }}
          body: |
            ${{ steps.changelog.outputs.notes }}
            
            ## Installation
            
            ```toml
            [dependencies]
            rtoon = "${{ steps.get_version.outputs.version }}"
            ```
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

